
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 21 2026 14:19:33 IST (Mar 21 2026 08:49:33 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, q);
  input clk, rst;
  output [3:0] q;
  wire clk, rst;
  wire [3:0] q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  SDFFRHQX2 \q_reg[3] (.RN (n_6), .CK (clk), .D (n_1), .SI (q[3]), .SE
       (n_4), .Q (q[3]));
  DFFRHQX2 \q_reg[2] (.RN (n_6), .CK (clk), .D (n_5), .Q (q[2]));
  OA21XL g85__2398(.A0 (q[2]), .A1 (n_2), .B0 (n_4), .Y (n_5));
  DFFRHQX2 \q_reg[1] (.RN (n_6), .CK (clk), .D (n_3), .Q (q[1]));
  AOI2BB1XL g88__5107(.A0N (q[0]), .A1N (q[1]), .B0 (n_2), .Y (n_3));
  NAND2XL g87__6260(.A (q[2]), .B (n_2), .Y (n_4));
  AND2X1 g90__4319(.A (q[1]), .B (q[0]), .Y (n_2));
  CLKINVX1 g91(.A (q[3]), .Y (n_1));
  INVXL g92(.A (rst), .Y (n_6));
  DFFRX2 \q_reg[0] (.RN (n_6), .CK (clk), .D (n_0), .Q (q[0]), .QN
       (n_0));
endmodule

