/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID c2slab.iiitt.ac.in)
#  Generated on:      Sat Mar 21 19:42:13 2026
#  Design:            counter
#  Command:           saveNetlist ../outputs/counter_final.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 21 2026 14:19:33 IST (Mar 21 2026 08:49:33 UTC)
// Verification Directory fv/counter 
module counter (
	clk, 
	rst, 
	q);
   input clk;
   input rst;
   output [3:0] q;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;

   SDFFRHQX2 \q_reg[3]  (.CK(clk),
	.D(n_1),
	.Q(q[3]),
	.RN(n_6),
	.SE(n_4),
	.SI(q[3]));
   DFFRHQX2 \q_reg[2]  (.CK(clk),
	.D(n_5),
	.Q(q[2]),
	.RN(n_6));
   OA21XL g85__2398 (.A0(q[2]),
	.A1(n_2),
	.B0(n_4),
	.Y(n_5));
   DFFRHQX2 \q_reg[1]  (.CK(clk),
	.D(n_3),
	.Q(q[1]),
	.RN(n_6));
   AOI2BB1XL g88__5107 (.A0N(q[0]),
	.A1N(q[1]),
	.B0(n_2),
	.Y(n_3));
   NAND2XL g87__6260 (.A(q[2]),
	.B(n_2),
	.Y(n_4));
   AND2X1 g90__4319 (.A(q[1]),
	.B(q[0]),
	.Y(n_2));
   CLKINVX1 g91 (.A(q[3]),
	.Y(n_1));
   INVXL g92 (.A(rst),
	.Y(n_6));
   DFFRX2 \q_reg[0]  (.CK(clk),
	.D(n_0),
	.Q(q[0]),
	.QN(n_0),
	.RN(n_6));
endmodule

